version: '3'
services:
  openbas-dev-pgsql:
    container_name: openbas-dev-pgsql
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: openbas
    ports:
      - "5432:5432"
    restart: unless-stopped
  openbas-dev-minio:
    container_name: openbas-dev-minio
    image: minio/minio:RELEASE.2025-06-13T11-33-47Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: unless-stopped
  openbas-dev-rabbitmq:
    container_name: openbas-dev-rabbitmq
    image: rabbitmq:4.1-management
    volumes:
      - type: bind
        source: rabbitmq.conf
        target: /etc/rabbitmq/rabbitmq.conf
    restart: unless-stopped
    ports:
      - "5672:5672"
      - "15672:15672"
