services:
  openbas:
    environment:
      - INJECTOR_CALDERA_ENABLE=true
      - INJECTOR_CALDERA_URL=${CALDERA_URL:-http://caldera:8888}
      - INJECTOR_CALDERA_PUBLIC_URL=${CALDERA_PUBLIC_URL:-http://localhost:8888}
      - INJECTOR_CALDERA_API_KEY=${CALDERA_API_KEY:-ChangeMe}
    depends_on:
      caldera:
        condition: service_healthy