services:
  caldera:
    image: openbas/caldera-server:5.1.0
    restart: always
    ports:
      - "8888:8888" # If you change the host port (the left one) do not forget to update CALDERA_PUBLIC_URL everywhere
    environment:
      CALDERA_URL: ${CALDERA_PUBLIC_URL:-http://localhost:8888}
    volumes:
      - type: bind
        source: ./caldera.yml
        target: /usr/src/app/conf/local.yml
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8888" ]
      interval: 10s
      timeout: 5s
      retries: 5